// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kribifrbfiaxrnbkezyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyaWJpZnJiZmlheHJuYmtlenl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDgwNDcsImV4cCI6MjA2NjAyNDA0N30.7nwqEl6j_Pen41dvcuhAZh0Gp5mJS7nsxIMC7YkYh6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});